package com.alatauBot.entity.enums;

public enum WaitingType {

    START, CHOOSE_BACK, GET_TEG_LIST, DELETE_EMPLOYEE, ADD_EMPLOYEE, DELETE_EMPLOYEE2, ADD_TEG, ADD_TEG_KZ, CHOOSE_DEPARTMENTS, SET_REPORT, CHOICE_OPTION, NEXT_KEYBOARD, COMMAND_EDITOR, SET_TEXT_DESC_BACK, UPDATE_BUTTON, UPDATE_TEXT, UPDATE_BUTTON_LINK, UPDATE_FILE,
    SET_FULL_NAME, SET_PHONE_NUMBER, CHOSE_BUTTON_BUTTON, EDIT_UPDATE_TEXT, EDIT_UPDATE_PHOTO, SET_STRUCTURE_DEPARTMENTS_INFO, EDIT_UPDATE_DEPARTMENTS_TEXT, EDIT_UPDATE_DEPARTMENTS_PHOTO, EDIT_CATEGORY_NAME2,
    SET_QUESTION, WAIT, CHOOSE_RECEPTION, SET_CHOSE, SET_TYPE, SET_TYPE_TYPE, SET_LOCATION, CHOSE_RECEPTION_BUTTON, SET_ADMIN_BY_PHONE, SET_PHOTO_OR_VIDEO, SET_TEG, EDIT_CATEGORY, EDIT_CATEGORY2, OP_CATEGORY,
    SET_IIN, SET_OTHER_PROF_COURSES, SET_OTHER_SOCIAL_NEEDS, EVENT, SET_TEXT, SET_PHOTO, SET_STRUCTURE_INFO, DELETE_ADMIN, ADD_ADMIN, SET_RECEPTION_TYPE, SET_RECEPTION_TEG, EDIT_CATEGORY_NAME, EDIT_TEG, PRESS_COMMAND, START_DATE, END_DATE, SEND_MESS_RECEPTION_TYPE, SET_FILE, SET_TEXT_DESC, SET_TYPE_123, SET_QUESTION_BACK, SET_QUESTION_TEXT,
    SET_TEXT_CAUSE_TO_RENEWAL,SET_RENEWAL_DEADLINE, CHOOSE_REQUEST_RESPONSIBLE, REQUEST_RESPONSIBLE_HANDLER,ADD_DIRECTOR,CHOOSE_REQUEST_FOR_APPROVAL,CHOOSE_REQUEST_RESPONSIBLE_NACH,REQUESTS_FOR_APPROVAL,
}
